apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret-tls
    namespace: demo-namespace
type: kubernetes.io/tls
data:
    tls.crt: base64 encoded cert content
    tls.key: base64 encoded key content